# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

DCTdenoising <- function(ipixelsR, width, height, sigma, flag_dct16x16) {
    .Call(`_imagerExtra_DCTdenoising`, ipixelsR, width, height, sigma, flag_dct16x16)
}

piecewise_transformation <- function(data, F, N, smax, smin, max, min, max_range, min_range) {
    .Call(`_imagerExtra_piecewise_transformation`, data, F, N, smax, smin, max, min, max_range, min_range)
}

screened_poisson_dct <- function(data, L) {
    .Call(`_imagerExtra_screened_poisson_dct`, data, L)
}

saturateim <- function(data, max_im, min_im, max_range, min_range) {
    .Call(`_imagerExtra_saturateim`, data, max_im, min_im, max_range, min_range)
}

